name: flutterlicensenow
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  sqflite: any
  path_provider: any
  path:
  signed_spacing_flex :
  provider: ^5.0.0
  swipe_to:
  # add this line to your dependencies
  fluttertoast: ^8.2.2

    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_logo.png
    - assets/images/rto_main_back.png
    - assets/images/rate.png
    - assets/images/share.png
    - assets/images/question_bank.png
    - assets/images/mock_test_icon.png
    - assets/images/exam_test_icon.png
    - assets/images/service.png
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/img7.jpg
    - assets/images/img8.jpg
    - assets/images/img9.jpg
    - assets/images/img10.jpg
    - assets/images/img12.jpg
    - assets/images/img13.jpg
    - assets/images/img14.jpg
    - assets/images/img15.jpg
    - assets/images/img16.jpg
    - assets/images/img17.jpg
    - assets/images/img18.jpg
    - assets/images/img19.jpg
    - assets/images/img20.jpg
    - assets/images/img21.jpg
    - assets/images/img22.jpg
    - assets/images/img23.jpg
    - assets/images/img24.jpg
    - assets/images/img25.jpg
    - assets/images/img26.jpg
    - assets/images/img27.jpg
    - assets/images/img28.jpg
    - assets/images/img29.jpg
    - assets/images/img30.jpg
    - assets/images/img31.jpg
    - assets/images/img32.jpg
    - assets/images/img33.jpg
    - assets/images/img34.jpg
    - assets/images/img35.jpg
    - assets/images/img36.jpg
    - assets/images/img37.jpg
    - assets/images/img38.jpg
    - assets/images/img39.jpg
    - assets/images/img40.jpg
    - assets/images/img41.jpg
    - assets/images/img42.jpg
    - assets/images/img43.jpg
    - assets/images/img44.jpg
    - assets/images/img45.jpg
    - assets/images/img46.jpg
    - assets/images/img47.jpg
    - assets/images/img48.jpg
    - assets/images/img49.jpg
    - assets/images/img50.jpg
    - assets/images/img51.jpg
    - assets/images/img52.jpg
    - assets/images/img53.jpg
    - assets/images/img54.jpg
    - assets/images/img55.jpg
    - assets/images/img56.jpg
    - assets/images/img57.jpg
    - assets/images/img58.jpg
    - assets/images/img59.jpg
    - assets/images/img60.jpg
    - assets/images/img61.jpg
    - assets/images/img62.jpg
    - assets/images/img65.jpg
    - assets/images/img66.jpg
    - assets/images/img67.jpg
    - assets/images/img68.jpg
    - assets/images/img69.jpg
    - assets/images/img69.jpg
    - assets/images/img70.jpg
    - assets/images/img71.jpg
    - assets/images/img72.jpg
    - assets/images/img73.jpg
    - assets/images/img74.jpg
    - assets/images/img77.jpg
    - assets/images/img78.jpg
    - assets/images/img79.jpg
    - assets/images/img80.jpg
    - assets/images/img81.jpg
    - assets/images/img82.jpg
    - assets/images/img83.jpg
    - assets/images/img84.jpg
    - assets/images/img118.jpg
    - assets/images/img138.jpg




  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
